apiVersion: v1
kind: ServiceAccount
metadata:
  name: vxlan
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vxlan
  namespace: kube-system
  labels:
    tier: node
    app: vxlan
spec:
  selector:
    matchLabels:
      app: vxlan
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: vxlan
    spec:
      hostNetwork: true
      serviceAccountName: vxlan
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: vxlan
        image: ghcr.io/trevex/homelab@sha256:ab35d97d60dedd628e1b7f2fe2564580389ad04ff4b653b28b3dbd2d9b883eb3
        securityContext:
          privileged: true
        volumeMounts:
        - name: cnibin
          mountPath: /host/opt/cni/bin
      volumes:
        - name: cnibin
          hostPath:
            path: /opt/cni/bin

