apiVersion: v1
kind: ServiceAccount
metadata:
  name: vxlan
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vxlan
  namespace: kube-system
  labels:
    tier: node
    app: vxlan
spec:
  selector:
    matchLabels:
      app: vxlan
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: vxlan
    spec:
      hostNetwork: true
      serviceAccountName: vxlan
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: vxlan
        image: ghcr.io/trevex/homelab@sha256:87b4324f939f184defb40fcda8422880f18ce442371006174da4cdab0efa324a
        securityContext:
          privileged: true
        volumeMounts:
        - name: cnibin
          mountPath: /host/opt/cni/bin
      volumes:
        - name: cnibin
          hostPath:
            path: /opt/cni/bin

