---
# apiVersion: "k8s.cni.cncf.io/v1"
# kind: NetworkAttachmentDefinition
# metadata:
#   name: vxlan-a
# spec:
#   config: '{
#   "type": "vxlan",
#   "vni": 300,
#   "ipam": {
#     "type": "whereabouts",
#     "range": "172.16.32.0/24"
#   }
# }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vxlan-a
spec:
  config: '{
  "type": "vxlan",
  "vni": 300,
  "addr": "172.16.32.1/24"
}'
---
apiVersion: v1
kind: Pod
metadata:
  name: vxlan-a
  annotations:
    k8s.v1.cni.cncf.io/networks: vxlan-a
spec:
  containers:
  - name: test
    image: centos/tools
    imagePullPolicy: IfNotPresent
    command:
    - /sbin/init
  nodeSelector:
    kubernetes.io/hostname: compute-1
---
# apiVersion: "k8s.cni.cncf.io/v1"
# kind: NetworkAttachmentDefinition
# metadata:
#   name: vxlan-b
# spec:
#   config: '{
#   "type": "vxlan",
#   "vni": 300,
#   "ipam": {
#     "type": "whereabouts",
#     "range": "172.16.32.0/24"
#   }
# }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vxlan-b
spec:
  config: '{
  "type": "vxlan",
  "vni": 300,
  "addr": "172.16.32.2/24"
}'
---
apiVersion: v1
kind: Pod
metadata:
  name: vxlan-b
  annotations:
    k8s.v1.cni.cncf.io/networks: vxlan-b
spec:
  containers:
  - name: test
    image: centos/tools
    imagePullPolicy: IfNotPresent
    command:
    - /sbin/init
  nodeSelector:
    kubernetes.io/hostname: compute-2
