apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources: # no patches required as we are using cilium
  # multus
  # - https://github.com/k8snetworkplumbingwg/multus-cni/raw/v4.0.2/deployments/multus-daemonset-thick.yml
  - https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/a373a2286d3f74d2b0ba05f2592c2820f0087053/deployments/multus-daemonset-thick.yml
  # whereabouts
  - https://github.com/k8snetworkplumbingwg/whereabouts/raw/v0.6.3/doc/crds/whereabouts.cni.cncf.io_overlappingrangeipreservations.yaml
  - https://github.com/k8snetworkplumbingwg/whereabouts/raw/v0.6.3/doc/crds/whereabouts.cni.cncf.io_ippools.yaml
  - https://github.com/k8snetworkplumbingwg/whereabouts/raw/v0.6.3/doc/crds/daemonset-install.yaml
