apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  # multus (patch for k3s below)
  - https://github.com/k8snetworkplumbingwg/multus-cni/raw/v4.0.2/deployments/multus-daemonset-thick.yml
  # whereabouts (patch for k3s below)
  - https://github.com/k8snetworkplumbingwg/whereabouts/raw/v0.6.3/doc/crds/whereabouts.cni.cncf.io_overlappingrangeipreservations.yaml
  - https://github.com/k8snetworkplumbingwg/whereabouts/raw/v0.6.3/doc/crds/whereabouts.cni.cncf.io_ippools.yaml
  - https://github.com/k8snetworkplumbingwg/whereabouts/raw/v0.6.3/doc/crds/daemonset-install.yaml

patches:
  - path: multus-patch.yaml
    target:
      kind: DaemonSet
      name: kube-multus-ds
      namespace: kube-system
  - path: whereabouts-patch.yaml
    target:
      kind: DaemonSet
      name: whereabouts
      namespace: kube-system

