apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds
  namespace: kube-system
spec:
  template:
    spec:
      volumes:
        - name: cni
          hostPath:
            path: /var/lib/rancher/k3s/agent/etc/cni/net.d
        - name: cnibin
          hostPath:
            path: /var/lib/rancher/k3s/data/current/bin
      # containers:
      #   - name: kube-multus
      #     image: ghcr.io/k8snetworkplumbingwg/multus-cni:v4.0.2
      # initContainers:
      #   - name: install-multus-binary
      #     image: ghcr.io/k8snetworkplumbingwg/multus-cni:v4.0.2

