apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - route-reflector.yaml
  - vtep.yaml

images:
- name: controller
  newName: quay.io/metallb/frr-k8s
  newTag: v0.0.8
- name: quay.io/metallb/frr-k8s
  newTag: v0.0.8
